language: java
jdk:
- openjdk8
dist: xenial
node_js:
- '10'

cache:
  yarn: true
  directories:
  - node_modules
before_install:
- pyenv install 3.6
- pyenv global system 3.6
- pip3 install --user codecov
- nvm install 10.14.2
- npm install -g yarn
- yarn install
install:
- cd student-mobility-broker-client && yarn install && cd ..
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
- cd student-mobility-broker-client && yarn build && yarn test && cd ..
after_script:
- pkill mongod
after_success:
- codecov
